### ISSUE TITLE
ssh unable to authenticate with Ubuntu 22.04

### ISSUE THREAD

**Issue by quadespresso** [Mirantis/mcc#366]
## Overview

Launchpad hits an `ssh: unable to authenticate` issue when dealing with Ubuntu 22.04.

Of particular interest: I've hit this same issue with Packer, testkit, and terraform. All tools that are written in Go.

## Details

The issue at hand:

```bash
[2022-05-04 18:38:06] INFO ==> Running phase: Open Remote Connection
[2022-05-04 18:38:07] DEBU phase 'Open Remote Connection' took 0s
[2022-05-04 18:38:07] DEBU tracking analytics event 'Check For Upgrades'
[2022-05-04 18:38:07] DEBU tracking analytics event 'Cluster Apply Failed'
[2022-05-04 18:38:07] INFO See /Users/jimcarroll/.mirantis-launchpad/cluster/testkit/apply.log for more logs
[2022-05-04 18:38:07] FATA failed on 1 hosts:
[2022-05-04 18:38:07]  - [ssh] 34.219.84.22:22: All attempts fail:
[2022-05-04 18:38:07] #1: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

(Pardon the leading timestamps... those are part of my personal setup.)

My launchpad.yaml:

```yaml
"apiVersion": "launchpad.mirantis.com/mke/v1.3"
"kind": "mke"
"metadata":
  "name": "testkit"
"spec":
  "cluster":
    "prune": false
  "hosts":
    - "hooks":
        "apply":
          "after":
            - ""
          "before":
            - ""
      "role": "manager"
      "ssh":
        "address": "34.219.84.22"
        "keyPath": "~/.ssh/jimc-core-oregon.pem"
        "user": "docker"
  "mcr":
    "channel": "test"
    "installURLLinux": "https://get.mirantis.com/"
    "installURLWindows": "https://get.mirantis.com/install.ps1"
    "repoURL": "https://repos-internal.mirantis.com"
    "version": "20.10.11"
  "mke":
    "adminPassword": "--REDACTED--"
    "adminUsername": "admin"
    "imageRepo": "docker.io/mirantis"
    "installFlags":
      - "--default-node-orchestrator=kubernetes"
      - "--cloud-provider=aws"
    "upgradeFlags":
      - "--force-recent-backup"
      - "--force-minimums"
    "version": "3.5.3"
```

## Manual ssh check

Added verification: I can confirm that I can ssh into the same instance (below) that fails with launchpad (above):

```bash
❯ ssh -i ~/.ssh/jimc-core-oregon.pem docker@34.219.84.22
Warning: Permanently added '34.219.84.22' (ED25519) to the list of known hosts.
Welcome to Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1005-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed May  4 23:52:19 UTC 2022

  System load:  0.0               Processes:             108
  Usage of /:   5.2% of 38.60GB   Users logged in:       0
  Memory usage: 3%                IPv4 address for ens5: 172.31.14.61
  Swap usage:   0%

 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

0 updates can be applied immediately.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

Last login: Wed May  4 23:38:39 2022 from 47.186.105.173
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

docker@ip-172-31-14-61:~$ grep PRETTY /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
```

## See also

- <https://github.com/hashicorp/packer/issues/11733#issuecomment-1117581578>
- <https://groups.google.com/g/golang-announce/c/-cp44ypCT5s/m/wmegxkLiAQAJ>
- PRODENG-1722 [testkit create fails with Ubuntu 22.04 - ssh unable to authenticate](https://mirantis.jira.com/browse/PRODENG-1722)
