### ISSUE TITLE
UCP configuration

### ISSUE THREAD

**Issue by jnummelin** [Mirantis/mcc#8]
We need a way to pass UCP configs forward from mcc too to UCP bootstrapper. I see two options for this:

### Break UCP config into the same `cluster.yaml`

This would essentially mean that user can put all the configs into the same file. The config could look something like:
```
hosts:
- address: 1.2.3.4
  user: root
ucp:
  version: 3.3.0-rc1
  auth:
    backend: managed
  registries:

```
Good:
- User has single place to configure everything
- We can validate the UCP level config
Bad:
- We need to keep this in sync with UCP versions as we need to be able to parse everything

### Feed the config via toml

One option is to feed in the config as separate toml file/structure. Currently UCP can take in the toml config as a whole in install phase so mcc could read the "external" file and feed it in. The cluter config could look something like:
```
hosts:
- address: 1.2.3.4
  user: root
ucp:
  version: 3.3.0-rc1
  config: /path/to/ucp.toml
```

Good:
- No need to keep mcc internals in-sync with UCP config options
Bad:
- User needs to manage two config files for the cluster
- Not possible to validate the UCP toml config at install time

---

My personal first approach would be to take in the whole toml through a file and feed it into the [UCP bootsrap process](https://docs.docker.com/ee/ucp/admin/configure/ucp-configuration-file/#apply-an-existing-configuration-file-at-install-time). It'll be much quicker route, at least for the first spike.
